FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# SI-API

Polls is a simple API allowing consumers to view polls and vote in them.



## ZIXUN - 赛事信息 [/matchInfo/1139]
 根据matchnews_id查询赛事信息
### matchInfo/...matchnews_id... [GET]
+ Response 200 (application/json)

        {
            "matchId":1139,
            "homeName":"拉普拉塔体操",
            "awayName":"拉斐拉竞技",
            "homeImage":"web_img/zhudui.png",
            "awayImage":"web_img/kedui.png",
            "weather":"雨",
            "homeFormation":"4-2-1-3",
            "awayFormation":"4-2-3-1",
            "homeStar":3,
            "awayStar":4,
            "homeLatest5":"2X212",
            "homeAtHomeLatest5":"11X2X",
            "awayLatest5":"11X21",
            "awayAtAwayLatest5":"2X21X",
            "homeSummary":"拉普拉塔体操上轮客胜沙兰迪兵工厂，联赛斩获4连胜，近9轮6胜3平不败，周中球队在杯赛中点球淘汰圣达菲联；后卫奥雷哈和替补前锋孔特雷拉斯因伤周中未随队出征，周末需要等待检查，后卫利希特养伤。戈多伊克鲁斯上轮大胜北古斯路，连续6个主场不败，不过近5个客场1平4负且没有进球；前锋阿约韦、后卫维埃拉解禁待命，前锋梅尔卡多有伤。",
            "awaySummary":"拉斐拉竞技客场面对纽维尔老男孩。上半场比赛双方没有取得进球，半场以0-0的比分结束；下半场比赛双方各进1球，最终拉斐拉竞技客场1-1战平纽维尔老男孩。拉斐拉竞技近期表现不佳，近6场比赛都没有取得胜利，球队目前状态十分糟糕。本场比赛，拉斐拉竞技主场面对近况出色的竞技俱乐部，受到近期不胜的影响，拉斐拉竞技主场或会不敌对手。拉斐拉竞技是一支来自阿根廷圣塔菲省拉斐拉市的足球队，球队创始于1970年。2002-03 赛季，拉斐拉竞技从乙级联赛突围冲上甲级。次年在甲级联赛降级附加赛中落败，回到乙级联赛。09年球队又有一次冲上甲级的机会，再第一回合3:0获胜的情 况下，居然第二回合以同样比分输了个0:3被拉普拉塔体操队所阻，只得继续停留在乙级联赛。2011年5月21日，球队终于通过打败图库曼竞技队，再次回 到甲级联赛。",
            "homeinjury":"沙柏迪利安度,S.戈加,法昆多.奧雷加",
            "homesuspended":"沙柏迪利安度,S.戈加,法昆多.奧雷加",
            "homepossibleinjury":"沙柏迪利安度,S.戈加,法昆多.奧雷加",
            "awayinjury":"沙柏迪利安度,S.戈加,法昆多.奧雷加",
            "awaysuspended":"沙柏迪利安度,S.戈加,法昆多.奧雷加",
            "awaypossibleinjury":"沙柏迪利安度,S.戈加,法昆多.奧雷加",
            
            "matchDate":"2016-09-20 08:15:00",
            "leagueName":"阿根廷甲级联赛",
            
            
            "homeBattleFormation":[{
            "position":"门将",
            "name":"曼努埃尔.加西亚",
            "playerid":1213,
            "importance":"关键球员"
           },
           {
            "position":"守门员",
            "name":"阿里亚斯·马丁",
            "playerid":1213,
           "importance":"关键球员"
           },
           {
           "position":"后卫",
           "name":"C.拉莫斯",
           "playerid":1213,
           "importance":"普通球员"
           }],
           
           "awayBattleFormation":[{
           "position":"门将",
            "name":"曼努埃尔.加西亚",
            "playerid":1213,
            "importance":"关键球员"
           },
           {
            "position":"守门员",
            "name":"阿里亚斯·马丁",
            "playerid":1213,
           "importance":"关键球员"
           },
           {
           "position":"后卫",
           "name":"C.拉莫斯",
           "playerid":1213,
           "importance":"普通球员"
           }]
        }
        
        
        
## ZIXUN - 球员发挥统计 [/player/1213]
 根据球员id查询球员发挥统计
### player/...playerid... [GET]
+ Response 200 (application/json)

        
         {  
           "playerImg":"web_img/0.jpg",
           "playerName":"曼努埃尔.加西亚",
           "importance":"关键球员",
           "position":"守门员",
           "nationality":"美国",
           "team":"切希尔",
           "playerid":1213,
           "matchNum":5,
           "firstNum":3,
           "goalNum":6,
           "yellNum":0,
           "redNum":2,
           "fiveGames":[{
                "homeName":"切尔西",
                "awayName":"利物浦",
                "score":"1:2",
                "bunko":"赢",
                "expression":"4-5-6-7"
           },{
                "homeName":"切尔西",
                "awayName":"利物浦",
                "score":"1:2",
                "bunko":"输",
                "expression":"1-2-4-5-6-7"
           },{
                "homeName":"切尔西",
                "awayName":"利物浦",
                "score":"1:2",
                "bunko":"赢",
                "expression":"1-2-3-4-5"
           },{
                "homeName":"切尔西",
                "awayName":"利物浦",
                "score":"1:2",
                "bunko":"输",
                "expression":"1-7"
           },{
                "homeName":"切尔西",
                "awayName":"利物浦",
                "score":"1-2",
                "bunko":"输",
                "expression":"1-2-3-4-5-6-7"
           }]
           }
        
        
## ZIXUN - 球队表现对比 [/matches/1139]
 根据matchnews_id查询球队表现对比
### matches/...matchnews_id... [GET]
+ Response 200 (application/json)

        
           {
              "homeName":"拉普拉塔体操",
              "awayName":"拉斐拉竞技",
              "homeGoalAverage":0.2,
              "awayGoalAverage":1.4,
              "homeFumbleAverage":1.1,
              "awayFumbleAverage":1.2,
              "homeFumbleNo":2,
              "awayFumbleNo":2,
              "homeScoreNo":1.3,
              "awayScoreNo":1.12,
              "keyEvents":[{
                "minute":10,
                "eventType":1,
                "eventDesc":"进球",
                "team":2,
                "playerid":33
                },{
                "minute":21,
                "eventType":5,
                "eventDesc":"黄牌",
                "team":1,
                 "playerid":45
                },{
                "minute":43,
                "eventType":6,
                "eventDesc":"红牌",
                "team":2,
                 "playerid":12
                 },{
                "minute":55,
                "eventType":6,
                "eventDesc":"红牌",
                "team":1,
                 "playerid":44
                 },{
                "minute":77,
                "eventType":1,
                "eventDesc":"进球",
                "team":1,
                 "playerid":12
                 }
                ]
           }
           
## SIZIXUN - id [/querySIMatchID/201610086007]
 根据uniqueID查询比赛对应的 matchnews_id
### querySIMatchID/...id... [GET]
+ Response 200 (application/json)

        {
          "caiex_matchnews_id":1139
           }
           
           
## ZIXUN - id [/queryMatchID/201610086007]
 根据uniqueID查询比赛对应的 matchID
### queryMatchID/...id... [GET]
+ Response 200 (application/json)

        {
          "matchID":1139
           }
           
           
## Game - MatchInfo [/tabList/getMatchInfo.shtml?dateVal={dateVal}&payout_type={payout_type}&player_id={player_id}]
  赛事列表
  
+ Parameters
    + dateVal: `2016-11-11` (timestamp) - picked date 
    + payout_type: `2` (number) - game type 1 or 2
    + player_id: `46` (number) - wechat id
  
### getMatchInfo for the default list [GET]
+ Response 200 (application/json)

        {
            "data":{
                "gameList":[
                    {
                        "auto_payout":1,
                        "auto_sync":1,
                        "awayUrl":null,
                        "bonus":0,
                        "championJoinState":0,
                        "champion_game_bonus":null,
                        "champion_game_state":1,
                        "champion_payout_state":1,
                        "champion_player_now":0,
                        "countGame":null,
                        "create_time":"2016-11-10 18:00:00",
                        "create_user":null,
                        "create_user_name":null,
                        "date":null,
                        "end_sign_time":"2016-11-11 00:00:00",
                        "freeJoinState":0,
                        "free_game_bonus":null,
                        "free_game_state":0,
                        "free_payout_state":1,
                        "free_player_now":0,
                        "game_id":201605242534,
                        "game_start_time":"2016-11-11 00:00:00",
                        "game_type":null,
                        "gpFree_id":null,
                        "gpGame_id":null,
                        "hadTcl":null,
                        "half_score":"1-1",
                        "hhadTcl":null,
                        "homeUrl":null,
                        "isclick":false,
                        "isclickFree":false,
                        "isclickGame":false,
                        "keyEvents":null,
                        "match_code":"201611104002",
                        "match_league":"\u56FD\u9645\u53CB\u8C0A",
                        "match_league_id":null,
                        "match_score":"2-1",
                        "match_state":2,
                        "match_teams":"\u5361\u5854\u5C14 vs \u4FC4\u7F57\u65AF",
                        "match_time":null,
                        "num":null,
                        "player_limit":null,
                        "price_limit":null,
                        "res":null,
                        "reward_percent":"50,30,10",
                        "sign_cost":1000,
                        "sport_type":1,
                        "sum_jackpot":0,
                        "w500":null
                    },
                    {
                        "auto_payout":1,
                        "auto_sync":1,
                        "awayUrl":null,
                        "bonus":0,
                        "championJoinState":0,
                        "champion_game_bonus":null,
                        "champion_game_state":1,
                        "champion_payout_state":1,
                        "champion_player_now":0,
                        "countGame":null,
                        "create_time":"2016-11-10 18:30:00",
                        "create_user":null,
                        "create_user_name":null,
                        "date":null,
                        "end_sign_time":"2016-11-11 00:30:00",
                        "freeJoinState":0,
                        "free_game_bonus":null,
                        "free_game_state":0,
                        "free_payout_state":1,
                        "free_player_now":0,
                        "game_id":201605242535,
                        "game_start_time":"2016-11-11 00:30:00",
                        "game_type":null,
                        "gpFree_id":null,
                        "gpGame_id":null,
                        "hadTcl":null,
                        "half_score":"2-0",
                        "hhadTcl":null,
                        "homeUrl":null,
                        "isclick":false,
                        "isclickFree":false,
                        "isclickGame":false,
                        "keyEvents":null,
                        "match_code":"201611104003",
                        "match_league":"\u7403\u4F1A\u53CB\u8C0A",
                        "match_league_id":null,
                        "match_score":"3-0",
                        "match_state":2,
                        "match_teams":"\u6155\u5C3C\u9ED11860 vs \u56E0\u6208\u5C14\u65BD\u5854\u7279",
                        "match_time":null,
                        "num":null,
                        "player_limit":null,
                        "price_limit":null,
                        "res":null,
                        "reward_percent":"50,30,10",
                        "sign_cost":1000,
                        "sport_type":1,
                        "sum_jackpot":0,
                        "w500":null
                    }
                ]
            },
            "result":{
                "resultCode":1,
                "resultMsg":null
            }
        }
        
## Game - Angular.js userService [/fallsList/getMatchUser.shtml?player_id={player_id}]
   游戏 获取用户信息
  
+ Parameters
    + player_id: `46` (number) - wechat id
  
### getMatchUser [GET]
+ Response 200 (application/json)

        {
            "data":{
                "birthday":"1996-06-21 09:53:49",
                "city":"",
                "headPicUrl":"http://www.caiex.com/img/logo.png",
                "money":100000.00,
                "phone":null,
                "player_id":46,
                "player_nickname":"\u9F99\u654F",
                "sex":2,
                "union_id":"oa7AjwoZHDzTU5poRpp778R1Qz-U",
                "update_time":"2016-11-09 07:23:29"
            },
            "result":{
                "resultCode":0,
                "resultMsg":null
            }
        }